= 终究还是去不了

2015年未能实现去日本的愿望 失落 自己很努力 但还是距离目标很大段的距离
自己所获得的经济能力不足以提供我去日本 工作一年了 钱虽不是万能 但是必须品

在生物群里面偷偷的看着他们 一起结伴成行到日本 一起看大家都很喜欢的乐队
真的很开心 我也很替他们开心 同时很妒忌 为何我连这一点的能力都没有 痛恨自己
以前还没说好一起去日本的时候 大家一起在群里吵吵闹闹的 很开心 每天都不寂寞
好像就有了一大群小伙伴跟你一起生活的样子 说的自己生活周边的事
大家一起笑 虽然不保证会一起哭 但也会替对方遇到不快乐的事伤心
而现在 我已经没有在群里说话的动力了 别人说去就能去 真的很羡慕
想去的日本没能去 然而群里还有个土豪在英国留学 去完日本又到欧洲各个国家旅游
欧游一直是我的愿望 别人随随便便就能实现 我也不是想靠别人 但我要实现不知道何时
不知名的等待 永远是最痛苦的

虽然自己现在有了工作 但是还是非常迷茫 我是否应该这样继续下去发展
我真的不知道 不知道如何选择自己的路 我应该走的是什么路
看见身边很多小伙伴都创业了 不过本钱也是家里人的 而我根本什么都没有

我也很想像他们一样创立自己的事业 但本钱我需要比其他人用更多的时间去打拼
可能一路打拼以来 自己的思想也会发生变化 然后随波逐流 做个上班族
我每次都跟我妈说 我可以去创立自己的事业 但比起其他人来说 我不能输 一次都不能
因为家里的经济不允许我输了再重来 我不跟别人的家庭一样 输了一次 起码还有家里做backup
我家里连做个backup的经济能力都没有 所以必须对每一次都非常谨慎 不能走错一步
我从大一的时候就开始有做各种创业的想法 而且有各种idea 同时我也有做各种方案出来
在一家创业公司上班了一年后 获得的经验发现我还是太嫩 如果大学的时候 就创业了 估计死得很惨
证明自己的等待是没有错的 一直工作 一直获取经验 一家创业的公司如果目标是大公司的话
必须一开始就打好基础 虽然现在的公司基础不是怎么好 而且方案也时不时就改变

== 以下粤语
进入了2015年初的时候 一位好朋友介绍了我去听电台 然后我现在每天都爱上一个节目
叱咤903"早霸王" 入面四个人都各有特点 而且每日都倾一啲生活平常噶野 而且时不时又讲翻以前香港噶野
真系好怀念以前噶香港 我属于珠三角长大的 而且细细个就被困系屋企 只能面对部电视 而啊阵又只会睇TVB同ATV
所以我对于旧时香港有一种情意结 特别系以前卡通片噶配音员 听到距地把声就觉得好怀念
虽然宜家都已经换左好多人 好多以前噶配音员都已经唔系度了 前排刚过左身噶林保全(哆啦A梦，叮当)
早霸王入面有小仪 森美 杰杰 西瓜 每日听到距地做节目 都好开心 而且每个礼拜五都有表白环节
几次有听到过有同性噶表白 真系好有勇气 睇到距地一起每日都好开心噶翻工做节目 好羡慕
有咩幸福过 翻工都可以日日笑 日日开心做自己钟意做噶野喈 系咪？
记得森美讲过一句说话好有意义的：好彩你蠢咋 如果唔系你系度就咩都唔系了
踩人地至于不忘加上一丝勉励

今年八月份中 我终于同一位网友见面了 认识了7年的 大家倾过两年噶生活事
但无联络左5年了 我6月份搵翻距 通过距朋友 然而距依然记得我 我好开心
当年我刚失恋无耐 走不去阴影 同时间又刚升高中 每个礼拜都依赖同距噶聊天黎开解自己
分散自己噶注意 让自己不寂寞 我又唔中意同身边认识噶人讲 因为自己唔肯去示弱
算系填补自己当年噶遗憾 当年想约距出黎 但距已经失踪了 所有可以联系噶方式都联系不上
今次可以约翻出黎 真系好开心 而且都好满足 距有问过我点解唔加微信 我觉得其实大家只系网友
虽然我当网友系朋友看待 但毕竟大家已经多年无倾过了 不再是当年的怪兽与超人了
今次出黎见面 我当面亲口讲声多谢 同埋令自己没有遗憾就OK了 毕竟大家生活没有任何交点
好多谢你博客入面噶怪兽 多谢你

同样八月底 有一件事令我好唔开心 系一个群入面认识左一个朋友 我本以为大家可以做好朋友
大家每日都系群入面调侃对方 而距又系一个有个女噶年轻妈咪 思想又开放 大家每日都倾下计
讲下以前噶野 几开心噶 当距话清远翻左花都 叫我出黎请下距女食饭 我之前有应承距噶
所以我无所谓 我可以 虽然比较远 而且啊度都比较杂 但OK 我无理由要人地带住个女出广州咖
然而我到了目的地 到了约好的钟点 距仍然没有出现 我等左好几个钟 仍然没有任何变化
微信发左几条 然后就被删好友了 电话打左好多个 一直无人接听 我就知道肯定有事了
我好失望 我系啊度逛左好多次 一直期待距只系未训醒 但结果都系0
距始终无出现 我唯有做车翻去了 系路上我自己一直打着问号一直帮距解释
但始终我过唔到自己啊关 距之前删过我两次好友 我都原谅距了 我同距讲过我唔允许有第三次
无论系意外定系特登噶 连自己交友噶自由都控制唔到 甘仲讲咩做朋友 然后之前都放过我一次飞机
今次又黎第二次 今次仲要系我请食饭 仲要我自己亲身去距啊度了 去花都要经过人和 人和很杂
但我都愿意上去了 仲要搭甘多个钟噶车 我都搭了 你都出唔到黎见我 点都讲唔过去啊 我已经尽力了
距系Q上面同我解释比人夹了 甘又如何 你多次应承过我噶野 无一样做到 但我应承噶你 全部做足
你教我点同你做朋友啊 我已经尽晒我一切能力 做晒我可以做噶 后尾我过左一个礼拜上去花都见一个朋友
然而心软 叫朋友msn比距 叫距出黎老地方等 然而距已经离开花都了 大家无缘分做朋友 只能就甘了
我唔舍得 但都无办法 就算继续落去 一样会令我多次失望 不如就甘算了 我连群都退埋 唔想日日见到 烦
一个月过去了 我终于心情平复了 我很重视友情 失去了一段友谊 我需要一段时间去平复自己 
建立一段友情不容易 维系一段友情更加不容易 但只有一方勉强维系 根本没有用
过去了就由距过去了 所有都重新黎过